# This Flow and Output collect logs from image builds running in the anvilops-dev namespace.
# Other versions of these resources are also created in users' namespaces to forward runtime logs from their pods.

apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: log-generator
spec:
  match:
    - select:
        labels:
          anvilops.rcac.purdue.edu/collect-logs: "true"
  localOutputRefs:
    - http
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: http
spec:
  http:
    endpoint: https://anvilops.rcac.purdue.edu/api/logs/ingest?type=build
    auth:
      # These credentials only allow build logs to be ingested.
      # Builds must run in our namespace because we don't want to copy our registry credentials and BuildKit TLS certs into tenant namespaces,
      # so to ingest their logs, we have to create a "master" logging configuration for all tenants' builds.
      username:
        value: anvilops-builder
      password:
        valueFrom:
          secretKeyRef:
            name: logging-ingest-secret
            key: secret
    content_type: application/jsonl # jsonl = newline-delimited JSON objects (https://jsonlines.org/)
    buffer:
      type: memory
      tags: time
      timekey: 1s
      timekey_wait: 0s
