---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: harbor-receiver
  namespace: anvilops-dev
spec:
  type: harbor
  secretRef:
    name: webhook-token
  resources:
    - kind: ImageRepository
      name: anvilops
