apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: anvilops
  namespace: anvilops-dev
spec:
  interval: 1m
  chart: charts/anvilops
  sourceRef:
    kind: GitRepository
    name: anvilops
  valuesFiles:
    - infra/anvilops/values.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: anvilops
  namespace: anvilops-dev
spec:
  interval: 1m
  chartRef:
    kind: HelmChart
    name: anvilops
    namespace: anvilops-dev
