apiVersion: v1
kind: Service
metadata:
  name: anvilops-postgres
  labels:
    app: anvilops-postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: dev
    app.kubernetes.io/version: 0.0.1
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: anvilops
    app.kubernetes.io/managed-by: fluxcd
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app: anvilops-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: anvilops-postgres
  namespace: anvilops-dev
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: dev
    app.kubernetes.io/version: 0.0.1
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: anvilops
    app.kubernetes.io/managed-by: fluxcd
spec:
  selector:
    matchLabels:
      app: anvilops-postgres
  serviceName: anvilops-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: anvilops-postgres
    spec:
      containers:
        - name: anvilops-postgres
          image: postgres:17
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
              subPath: anvilops-postgres-data
          env:
            - name: POSTGRES_USER
              value: anvilops
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
            - name: POSTGRES_DB
              value: anvilops
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: anvil-filesystem
        resources:
          requests:
            storage: 1Gi
