---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: anvilops
  namespace: anvilops-dev
spec:
  image: registry.anvil.rcac.purdue.edu/anvilops/anvilops
  interval: 1h
  provider: generic

