load('ext://restart_process', 'docker_build_with_restart')
load('ext://secret', 'secret_create_generic', 'secret_from_dict', 'secret_yaml_registry')
load('ext://dotenv', 'dotenv')
load('ext://deployment', 'deployment_create')
load('ext://helm_resource', 'helm_resource', 'helm_repo')
dotenv(fn='../backend/.env')

# Should the frontend and backend be deployed separately?
# If enabled, changes will apply much faster at the expense of a development environment that looks less like production.
separate_frontend_and_backend = True

# Deploy a minimal instance of the Grafana LGTM + Alloy stack to collect logs, metrics, and traces from AnvilOps
enable_monitoring = True

# Deploy Rancher locally
with_rancher = False

# Requires kubeVersion <1.35.0-0 
RANCHER_VERSION="v2.13.2"

# Increase timeout because ingress-nginx can take longer than 30s to install
update_settings(k8s_upsert_timeout_secs=60)

if separate_frontend_and_backend:
  docker_build(
    "anvilops-frontend", "../",
    dockerfile="./anvilops-frontend.Dockerfile",
    live_update=[
      sync("../frontend/src", "/app/src")
    ],
    only=["frontend", "openapi"]
  )
  docker_build(
    "anvilops/anvilops", "../",
    dockerfile="./anvilops-backend.Dockerfile",
    entrypoint=[
      "/usr/local/bin/node",
      "--experimental-strip-types",
      "--require", "/app/src/instrumentation.ts",
      "--watch"
    ],
    live_update=[
      sync("../backend/src", "/app/src"),
      run("touch /app/src/index.ts") # In some cases, Node doesn't detect file changes (i.e. the --watch flag doesn't work). This command seems to improve reliability of automatic restarts.
    ],
    only=["backend", "templates", "openapi"]
  )

  deployment_create(
    'anvilops-frontend',
    ports='80:5173'
  )
else:
  docker_build(
    "anvilops/anvilops", "../",
    only=["frontend", "backend", "swagger-ui", "templates", "openapi"]
  )
docker_build("anvilops/migrate-db", "../backend", dockerfile="../backend/prisma/Dockerfile", only=["package.json", "package-lock.json", "prisma", "prisma.config.ts"])
docker_build("anvilops/file-browser", "../filebrowser", match_in_env_vars=True)
docker_build("anvilops/dockerfile-builder", "../builders/dockerfile", match_in_env_vars=True)
docker_build("anvilops/railpack-builder", "../builders/railpack", match_in_env_vars=True)
docker_build("anvilops/helm-deployer", "../builders/helm", match_in_env_vars=True)
docker_build("anvilops/log-shipper", "../log-shipper", match_in_env_vars=True)

# Read the current kubeconfig, set the server to kubernetes.default.svc (a hostname accessible from within the cluster), and make it available to AnvilOps via a K8s secret
kubeconfig_str = local('kubectl config view --raw --minify', quiet=True)
kubeconfig = decode_yaml_stream(kubeconfig_str)
kubeconfig[0]["clusters"][0]["cluster"]["server"] = "https://kubernetes.default.svc"
modified_kubeconfig = encode_yaml_stream(kubeconfig)
k8s_yaml(secret_from_dict("kube-auth", inputs={'kubeconfig': modified_kubeconfig}))

# Get the hostname of Tilt's internal registry so that we can use it for AnvilOps user images 
registry_host = str(local("kubectl get cm -n kube-public local-registry-hosting -o jsonpath='{.data.localRegistryHosting\\.v1}' | grep hostFromClusterNetwork | cut -d \":\" -f2-")).strip()
print("Using local registry from within the cluster at " + registry_host)

k8s_yaml(secret_from_dict("oidc-credentials", inputs={
  'client-id': os.getenv('CLIENT_ID'),
  'client-secret': os.getenv('CLIENT_SECRET')
}))

k8s_yaml(secret_from_dict("github-app", inputs={
  'app-name': os.getenv('GITHUB_APP_NAME'),
  'app-id': os.getenv('GITHUB_APP_ID'),
  'client-id': os.getenv('GITHUB_CLIENT_ID'),
  'client-secret': os.getenv('GITHUB_CLIENT_SECRET'),
  'private-key': os.getenv('GITHUB_PRIVATE_KEY'),
  'webhook-secret': os.getenv('GITHUB_WEBHOOK_SECRET'),
  'base-url': os.getenv('GITHUB_BASE_URL'),
  'api-url': os.getenv('GITHUB_API_URL')
}))

# Deleting images isn't supported locally since we aren't running Harbor
k8s_yaml(secret_from_dict("image-delete-secret", inputs={'server': '__disabled_delete_server', 'username': '__disabled_delete_username', 'password': '__disabled_delete_password'}))
k8s_yaml(secret_yaml_registry("image-push-secret", flags_dict={'docker-server': registry_host, 'docker-username': '__disabled_push_username', 'docker-password': '__disabled_push_password'}))
k8s_yaml(secret_from_dict("image-pull-secret", inputs={'server': registry_host, 'username': '__disabled_pull_username', 'password': '__disabled_pull_password'}))

# Hard-code these values so that the secret value doesn't drift from the value that Postgres used when creating the user
k8s_yaml(secret_from_dict("postgres-credentials", inputs={'password': 'super-insecure-local-dev-password', 'field-encryption-key': '96WYSbPNEYi65gb8BRCzbf5ISIywNVV8Dm1rFCnRUFk='}))

yaml = helm(
  '../charts/anvilops',
  # The release name, equivalent to helm --name
  name='anvilops',
  # The namespace to install in, equivalent to helm --namespace
  namespace='default',
  # The values file to substitute into the chart.
  values=['./local-values.yaml'],
  # Values to override from the command-line
  set=['anvilops.env.otelEndpoint=http://lgtm:4317'] if enable_monitoring else []
)

parsed = decode_yaml_stream(yaml)

ingress_clusterip = "10.96.33.248"
for i, object in enumerate(parsed):
  if object["kind"] == "Deployment" and object["metadata"]["name"] == "anvilops":
    # Pass our registry hostname to AnvilOps as an environment variable
    for variable in object["spec"]["template"]["spec"]["containers"][0]["env"]:
      if variable["name"] == "REGISTRY_HOSTNAME":
        variable["value"] = registry_host
    
    # Alias Rancher hostname to the ingress controller ClusterIP
    hostAliases = object["spec"]["template"]["spec"].get("hostAliases", [])
    object["spec"]["template"]["spec"]["hostAliases"] = hostAliases + [{ "ip": ingress_clusterip, "hostnames": [ "rancher.127.0.0.1.nip.io" ] }]
    
    # Add an IN_TILT environment variable to redirect `localhost` registry lookups to the REGISTRY_HOSTNAME instead (see backend/src/lib/cluster/resources/logs.ts)
    object["spec"]["template"]["spec"]["containers"][0]["env"].append({"name": "IN_TILT", "value": "true"})
    if separate_frontend_and_backend:
      # Allow live_update to edit files in containers
      object["spec"]["template"]["spec"]["containers"][0]["securityContext"]["readOnlyRootFilesystem"] = False
      object["spec"]["template"]["spec"]["containers"][0]["securityContext"]["runAsNonRoot"] = False
      object["spec"]["template"]["spec"]["containers"][0]["securityContext"]["runAsUser"] = 0
      object["spec"]["template"]["spec"]["containers"][0]["securityContext"]["runAsGroup"] = 0
  # Make the BuildKit Daemon use insecure HTTP for our registry instead of the default HTTPS
  if object["kind"] == "Deployment" and object["metadata"]["name"] == "anvilops-buildkitd":
    object["spec"]["template"]["spec"]["volumes"].append({"name": "config", "configMap": {"name": "anvilops-buildkitd-config"}})
    object["spec"]["template"]["spec"]["containers"][0]["volumeMounts"].append({"name": "config", "mountPath": "/etc/buildkit"})
  # Make the ingress point to the frontend (which proxies to the backend when necessary) instead of to the backend
  if separate_frontend_and_backend and object["kind"] == "Ingress" and object["metadata"]["name"] == "anvilops":
    object["spec"]["rules"][0]["http"]["paths"][0]["backend"]["service"]["name"] = "anvilops-frontend"
  if object["kind"] == "Job":
    hostAliases = object["spec"]["template"]["spec"].get("hostAliases", [])
    object["spec"]["template"]["spec"]["hostAliases"] = hostAliases + [{ "ip": ingress_clusterip, "hostnames": [ "rancher.127.0.0.1.nip.io" ] }]

# Allow AnvilOps's buildkitd instance to use the built-in registry insecurely (over HTTP)
k8s_yaml(blob("""
apiVersion: v1
kind: ConfigMap
metadata:
  name: anvilops-buildkitd-config
data:
  buildkitd.toml: |
    [registry.\"""" + registry_host + """\"]
      http = true
"""))

k8s_yaml(encode_yaml_stream(parsed))

k8s_resource(workload='anvilops-postgres', port_forwards=[5432])

if with_rancher:
  # Requires kubeVersion <1.35.0-0
  # # view the rancher frontend at https://rancher.127.0.0.1.nip.io
  helm_repo('rancher_repo', 'https://releases.rancher.com/server-charts/latest')
  helm_resource(
    'rancher',
    'rancher_repo/rancher',
    namespace='cattle-system',
    flags=[
      '--version=%s' % RANCHER_VERSION,
      '--set=hostname=rancher.127.0.0.1.nip.io',
      '--set=replicas=1',
      '--set=ingress.ingressClassName=nginx',
      '--set=tls=external',
      '--set=bootstrapPassword=insecurepassword123',
      '--create-namespace'
    ],
    resource_deps=['rancher_repo']
  )

# Install the Nginx ingress controller and forward localhost:3000, localhost:443
# forwarding to 0.0.0.0:443 instead of just 443 bypasses privileged port restriction on MacOS
# https://github.com/tilt-dev/tilt/issues/1909
helm_repo('ingress-nginx_repo', 'https://kubernetes.github.io/ingress-nginx')
helm_resource(
  'ingress-nginx',
  'ingress-nginx_repo/ingress-nginx',
  namespace='ingress-nginx',
  flags=[
    '--create-namespace',
    '--set=controller.extraArgs.default-ssl-certificate=default/ingress-cert',
    '--set=controller.service.clusterIP=%s' % ingress_clusterip
  ],
  resource_deps=['ingress-nginx_repo'],
  port_forwards=('3000:80','0.0.0.0:443:443')
)

if enable_monitoring:
  deployment_create(
    name = "lgtm",
    image = "grafana/otel-lgtm:latest",
    ports = [
      "3000", # Grafana (dashboards)
      "4040", # Pyroscope (profiling)
      "4317", # OpenTelemetry (gRPC)
      "4318", # OpenTelemetry (HTTP)
      "9090"  # Prometheus (timeseries metrics)
    ],
    #env = [{"name": "ENABLE_LOGS_ALL", "value": "true"}]
  )

  k8s_resource("lgtm", port_forwards=["3001:3000"])
