apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: anvilops-allow-apps
  labels:
    {{- include "anvilops.commonLabels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "anvilops.buildkitd.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
    - Ingress
  egress:
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
          except:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
  ingress:
    - from:
      - podSelector:
          matchLabels:
            {{- include "anvilops.labels" . | ndindent 12 }}