apiVersion: v1
name: spilo
description: A minimal Spilo/Patroni HA Postgres deployment, adapted from https://github.com/zalando/spilo/kubernetes.
type: application
version: 0.1.3
annotations:
  anvilops-note: |
    Requires permission to create Roles and RoleBindings. Rancher Project Owners have this permission.
    The usernames of the superuser, admin, and replication user respectively are 'postgres', 'admin', and 'standby'.
  anvilops-watch-labels: application=spilo
  anvilops-values: |
    {
      "replicas": {
        "displayName": "Replicas",
        "type": "number",
        "default": "3",
        "required": true
      },
      "passwords": {
        "superuser": {
          "displayName": "Superuser Password",
          "type": "password",
          "random": true,
          "required": true
        },
        "replication": {
          "displayName": "Replication Password",
          "type": "password",
          "random": true,
          "required": true
        },
        "admin": {
          "displayName": "Admin Password",
          "type": "password",
          "random": true,
          "required": true
        }
      },
      "storage": {
        "className": {
          "displayName": "Storage Class",
          "type": "text",
          "noUpdate": true,
          "default": "standard",
          "required": true
        },
        "size": {
          "displayName": "Size",
          "type": "number",
          "noUpdate": true,
          "unit": "Gi",
          "default": "1",
          "required": true
        }
      }
    }