name: Security Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  security-scan:
    name: Run Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Tools
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          version: 2026.3.9
          install: true
          mise_toml: |
            [tools]
            trivy = "0.69.3"

      - name: Run Trivy
        run: trivy repository --exit-code 1 .
