name: Test (backend)
on:
  push:
    branches: [main]
    paths: ["backend/**"]
  pull_request:
    paths: ["backend/**"]

jobs:
  lint:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"
          cache-dependency-path: backend/package.json

      - name: Install NPM packages
        working-directory: backend
        run: npm ci

      - name: Run code generators
        working-directory: backend
        run: DATABASE_URL=placeholder npx prisma generate

      - name: Test
        working-directory: backend
        run: npm run test
